Repository hanaro7team1/frontend, pull requests merged in 2025-08, with the labels that each got.

#3 [Feat] icons & images 파일 생성
  public/icons/.keep
  public/icons/Ic_Account_lock_open.svg
  public/icons/Ic_Account_plus.svg
  public/icons/Ic_Arrow_down.svg
  public/icons/Ic_ChevronLeft_big.svg
  public/icons/Ic_ChevronLeft_white.svg
  public/icons/Ic_ChevronRight_small.svg
  public/icons/Ic_ChevronRight_white.svg
  public/icons/Ic_Client_verify.svg
  public/icons/Ic_Close.svg
  public/icons/Ic_ESG.svg
  public/icons/Ic_FestivalMenu.svg
  public/icons/Ic_HomeMenu.svg
  public/icons/Ic_House_big.svg
  public/icons/Ic_House_small.svg
  public/icons/Ic_Increase.svg
  public/icons/Ic_Lock_circle_fill.svg
  public/icons/Ic_Marked_event.svg
  public/icons/Ic_Phone_big.svg
  public/icons/Ic_Phone_circle_fill.svg
  public/icons/Ic_Phone_small.svg
  public/icons/Ic_Photo.svg
  public/icons/Ic_Point_map.svg
  public/icons/Ic_Price.svg
  public/icons/Ic_RealEstateMenu.svg
  public/icons/Ic_Room.svg
  public/icons/Ic_StayMenu.svg
  public/icons/Ic_Users.svg
  public/icons/ic_Chevron_big.svg
  public/images/.keep
  public/images/Img_AI.svg
  public/images/Img_AI_loading.svg
  public/images/Img_Festival.svg
  public/images/Img_Home_City_bottom.svg
  public/images/Img_Home_Countryside_Doctor.svg
  public/images/Img_Home_Countryside_New.svg
  public/images/Img_Mypage_Profile.svg
  public/images/Imv_Home_City_top.svg
Labels: design

#7 [Feat] atoms 컴포넌트 storybook 테스트 코드 작성
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/components/atoms/Button.tsx
  src/stories/atoms/Button.stories.tsx
  src/stories/atoms/Input.stories.tsx
  src/stories/atoms/ShadowBox.stories.tsx
  src/stories/atoms/Text.stories.tsx
Labels: docs

#12 [Feat] 사랑방 상세 페이지 퍼블리싱 구현
  public/icons/Ic_Arrow_down.svg
  public/icons/Ic_ChevronLeft_big.svg
  public/icons/Ic_ChevronLeft_white.svg
  public/icons/Ic_ChevronRight_small.svg
  public/icons/Ic_ChevronRight_white.svg
  public/icons/Ic_Close.svg
  public/icons/Ic_House_big.svg
  public/icons/Ic_House_small.svg
  public/icons/ic_Chevron_big.svg
  public/images/sample1.png
  public/images/sample2.png
  src/app/stays/[id]/page.tsx
  src/components/atoms/CarouselArrow.tsx
  src/components/atoms/Tag.tsx
  src/components/common/Carousel.tsx
  src/components/common/index.ts
  src/components/domain/add/steps/step5/Step5.tsx
  src/components/domain/stays/CityActionBar.tsx
  src/components/domain/stays/CountrysideActionBar.tsx
  src/components/domain/stays/EditButton.tsx
  src/components/domain/stays/StayActionBar.tsx
  src/components/domain/stays/StayDescription.tsx
  src/components/domain/stays/StayHeader.tsx
  src/components/domain/stays/StayInfoChips.tsx
  src/components/domain/stays/index.ts
  src/stories/atoms/ShadowBox.stories.tsx
Labels: feat, design

#14 [Feat] /admin/stays 관리자용 사랑방 목록 화면 퍼블리싱 완료
  src/app/admin/page.tsx
  src/app/admin/stays/page.tsx
  src/app/home/page.tsx
  src/app/main/page.tsx
  src/app/stays/page.tsx
  src/components/common/BottomTabNav.tsx
  src/components/common/Header.tsx
  src/components/domain/stays/RoomItem.tsx
  src/components/domain/stays/RoomList.tsx
  src/components/domain/stays/RoomStatusFilter.tsx
  src/components/domain/stays/RoomTypeFilter.tsx
  src/components/domain/stays/StayOptionFilters.tsx
  src/components/domain/stays/index.ts
  src/constants/common/BottomTabNav.ts
  src/types/stays.ts
Labels: feat, design

#16 [Feat] 도시 시니어 홈 & 시골 관리자 홈 페이지 UI 구현
  public/images/Img_Home_City.svg
  public/images/Img_Home_Countryside_Doctor.svg
  public/images/Img_Home_Countryside_New.svg
  public/images/Img_SIDO_LOGO.png
  public/images/Img_Splash.svg
  src/app/admin/page.tsx
  src/app/home/page.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/Text.tsx
  src/components/domain/admin/MenuTabs.tsx
  src/components/domain/admin/ReservationStats.tsx
  src/components/domain/admin/SIDOBankbook.tsx
  src/components/domain/admin/index.ts
  src/components/domain/home/LoanCard.tsx
  src/components/domain/home/ReservationButton.tsx
  src/components/domain/home/UpcommingStayCard.tsx
  src/components/domain/home/index.ts
  src/components/domain/main/.keep
  src/components/domain/stays/StayDescription.tsx
  src/components/domain/stays/StayHeader.tsx
  src/stories/atoms/Button.stories.tsx
Labels: feat, design

#19 [Feat] 숙박탭 숙박옵션 바텀시트
  package.json
  pnpm-lock.yaml
  public/dummy.ts
  src/app/admin/stays/page.tsx
  src/app/globals.css
  src/app/stays/page.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/index.ts
  src/components/domain/stays/BottomSheetLocation.tsx
  src/components/domain/stays/BottomSheetPeopleCount.tsx
  src/components/domain/stays/BottomSheetSchedule.tsx
  src/components/domain/stays/FilterRoomStatus.tsx
  src/components/domain/stays/FilterRoomType.tsx
  src/components/domain/stays/FilterStayOptions.tsx
  src/components/domain/stays/OpenDateModalBtn.tsx
  src/components/domain/stays/StayOptionFilters.tsx
  src/components/domain/stays/index.ts
  src/components/ui/accordion.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/sheet.tsx
  src/constants/stays/.keep
  src/constants/stays/stays.ts
  src/types/stays.ts
  src/utils/stays/.keep
  src/utils/stays/stays.ts
Labels: feat, design

#18 [Feat] 매물 상세 페이지 UI 구현
  public/icons/Ic_House.svg
  src/app/real-estates/[id]/page.tsx
  src/components/common/Carousel.tsx
  src/components/domain/realEstates/.keep
  src/components/domain/realEstates/BottomButton.tsx
  src/components/domain/realEstates/EstateDescription.tsx
  src/components/domain/realEstates/EstateHeader.tsx
  src/components/domain/realEstates/index.ts
  src/components/domain/stays/StayDescription.tsx
Labels: feat, design

#23 [Feat] 사랑방 목록 -> 상세 페이지 필터 연동 기능 구현 및 API 연동
  src/app/apis/stay-detail.ts
  src/app/stays/[id]/page.tsx
  src/app/stays/page.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/BottomTabNav.tsx
  src/components/domain/stays/BottomSheetPeopleCount.tsx
  src/components/domain/stays/BottomSheetSchedule.tsx
  src/components/domain/stays/CityActionBar.tsx
  src/components/domain/stays/CountrysideActionBar.tsx
  src/components/domain/stays/EditButton.tsx
  src/components/domain/stays/FilterRoomType.tsx
  src/components/domain/stays/FilterStayOptions.tsx
  src/components/domain/stays/RoomItem.tsx
  src/components/domain/stays/RoomList.tsx
  src/components/domain/stays/StayActionBar.tsx
  src/types/stays.ts
  src/utils/stays/stays.ts
Labels: feat, design
