Repository hanaro7team1/frontend, pull requests merged in 2025-09, with the labels that each got.

#31 [Feat] mypage 수정 및 함수 추가
  src/app/admin/mypage/contact/page.tsx
  src/app/admin/mypage/page.tsx
  src/app/admin/mypage/pwd/page.tsx
  src/app/admin/mypage/quit/page.tsx
  src/components/domain/admin/mypage/ChangeBox.tsx
  src/components/domain/admin/mypage/NoticeModal.tsx
Labels: feat, refactor

#35 [Feat] 축제 리스트 및 스크롤 함수 생성
  public/dummy.ts
  src/app/festivals/page.tsx
  src/components/domain/festivals/.keep
  src/components/domain/festivals/ListBox.tsx
Labels: feat, design, refactor

#38 [Feat] 사랑방 등록 api 연결 완료
  next.config.ts
  src/app/admin/mypage/contact/page.tsx
  src/app/admin/mypage/quit/page.tsx
  src/app/admin/stays/add/layout.tsx
  src/app/auth/signup/layout.tsx
  src/components/common/GifLoaders.tsx
  src/components/common/Modal.tsx
  src/components/domain/admin/add/StepProgressBar.tsx
  src/components/domain/admin/add/steps/step1/AdressSearchModal.tsx
  src/components/domain/admin/add/steps/step1/Step1.tsx
  src/components/domain/admin/add/steps/step2/PhotoGrid.tsx
  src/components/domain/admin/add/steps/step2/Step2.tsx
  src/components/domain/admin/add/steps/step3/Step3.tsx
  src/components/domain/admin/add/steps/step4/Step4.tsx
  src/components/domain/admin/add/steps/step5/Step5.tsx
  src/components/domain/admin/add/steps/step6/Step6.tsx
  src/components/domain/admin/add/wizard/WizardDataProvider.tsx
  src/components/domain/admin/add/wizard/WizardNav.tsx
  src/components/domain/admin/add/wizard/WizardProvider.tsx
  src/components/domain/reservations/CancelBtn.tsx
  src/components/domain/stays/CityActionBar.tsx
  src/components/domain/stays/CountrysideActionBar.tsx
  src/constants/admin/Admin.ts
  src/hooks/admin/useNumberInput.ts
  src/hooks/admin/usePhotoPreview.ts
  src/hooks/admin/usePhotoUpload.ts
  src/types/stays.ts
  src/types/wizard.ts
  src/utils/common/phoneHyphen.ts
  src/utils/stays/stays.ts
Labels: bug, feat, remove, design, refactor

#39 [Feat] 마이페이지 UI 수정 및 조회 & 수정 API 연결
  public/icons/Ic_Phone_big.svg
  public/icons/Ic_Phone_green.svg
  src/app/admin/mypage/contact/page.tsx
  src/app/admin/mypage/page.tsx
  src/app/admin/mypage/pwd/page.tsx
  src/app/apis/mypage.ts
  src/components/domain/admin/auth/PasswordField.tsx
  src/components/domain/admin/mypage/ChangeBox.tsx
  src/components/domain/admin/mypage/MypageLinkBox.tsx
  src/components/domain/admin/mypage/NoticeModal.tsx
  src/components/domain/admin/mypage/Profile.tsx
  src/components/domain/admin/mypage/index.ts
  src/lib/authValidation.ts
Labels: feat, design

#50 [Fix] 예약 색상 오류 등 수정
  src/app/reservations/page.tsx
  src/components/domain/reservations/FilterReserv.tsx
Labels: bug

#54 [Feat] 사진 업로드 안내멘트 추가
  src/components/domain/admin/add/steps/step2/Step2.tsx
  src/components/domain/admin/add/steps/step2/UploadInfo.tsx
  src/components/domain/admin/add/steps/step5/AiInfo.tsx
Labels: feat

#52 [Feat] 축제 리스트, 상세페이지 API 연결
  src/app/festivals/[id]/page.tsx
  src/app/festivals/page.tsx
  src/components/domain/festivals/ListBox.tsx
  src/hooks/api/useApi.ts
  src/types/festivals.ts
Labels: feat, refactor

#60 [Fix] 예약 리스트 페이지 api 연결
  src/app/reservations/page.tsx
  src/components/domain/reservations/ReservationCard.tsx
  src/types/reservation.ts
Labels: bug, refactor

#59 [Design] 시골 관리자 메인페이지 UI 수정
  src/app/admin/page.tsx
  src/components/domain/admin/MenuTabs.tsx
Labels: design

#63 [Fix] 예약 필터링 작동
  src/app/reservations/page.tsx
  src/components/domain/festivals/ListBox.tsx
  src/components/domain/reservations/FilterReserv.tsx
  src/constants/reservations/reservation.ts
  src/types/reservation.ts
Labels: bug

#66 [Fix] 사랑방 상세 조회: 로그인 유저 권한별로 예약 캡슐 다르게
  src/app/stays/[id]/page.tsx
Labels: bug

#72 [Design] 시골 관리자 홈 페이지와 사랑방 목록 페이지 UI 수정
  src/app/admin/mypage/contact/page.tsx
  src/app/admin/stays/page.tsx
  src/components/common/Header.tsx
  src/components/domain/admin/AddStayButton.tsx
  src/components/domain/admin/MenuTabs.tsx
  src/components/domain/admin/add/wizard/WizardNav.tsx
  src/components/domain/admin/index.ts
  src/components/domain/main/ReservationButton.tsx
  src/components/domain/stays/AdminRoomItem.tsx
Labels: design, refactor

#76 [Feat] Vitest 환경 구축 및 테스트 코드 추가
  __tests__/components/BottomSheet.test.tsx
  __tests__/components/Header.test.tsx
  __tests__/components/Modal.test.tsx
  __tests__/hooks/useAuth.test.ts
  __tests__/utils/bottomSheetTrigger.test.ts
  __tests__/utils/formatDate.test.ts
  package.json
  pnpm-lock.yaml
  tsconfig.json
  vitest.config.mts
  vitest.setup.ts
Labels: test

#84 [Fix] 축제 무한스크롤 삭제 및 롤백
  pnpm-lock.yaml
  src/app/festivals/page.tsx
  src/components/domain/festivals/FestivalList.tsx
Labels: bug
